class TXT:
    locale_setting = "French_France.1252"
    locale_country_code = "fr"
    locale_dayfirst = True

    long_date_format = "%a %d %b %y, %Hh%M"
    short_date_format = "%a %d %b %y"
    long_day_format = "le %A %d %B"

    log = "Log"
    new = "Nouveau"
    several_new = "Nouveaux"
    refresh = "Rafraichir"
    archives = "Archives"
    trash = "Poubelle"
    exit = " X "
    minimize = " _ "
    I_have_seen = "J'ai vu"
    ok = "OK"
    cancel = "Annuler"
    close = "Fermer"
    show = "Voir"
    delete_definitly = "Définitivement supprimer"
    delete = "Supprimer"
    archive = "Archiver"
    restore = "Restaurer"
    unarchive = "Désarchiver"
    edit = "Édition"
    event = "évènement"
    events = "évènements"
    init = "inititialisation"
    tracker_creation = "création suivi"
    driver_creation = "création pilote"
    updating = "MàJ..."
    updated = "MàJ"
    empty = "Vide"
    no_couriers = "Pas de Service Postaux"
    no_idship = "N° indéfini"
    invalid_idship = "N° mal formé"
    no_description = "Pas de description"
    error_courier_update = "Erreur MàJ"
    courier_doesnt_exist = "Service Postal inconnu"
    never = "jamais"
    ago = "il y a"

    idship = "N° de suivi"
    description = "Description"

    unknown_status = "Aucune information"
    status_error = "Erreur"
    default_product = "Envoi"
    package_product = "Colis"

    no_validation = "Pas de validation"
    digit = "chiffre"
    digits = "chiffres"
    letter = "lettre"
    letters = "lettres"
    zipcode = "code postal"
    from_ = "de"
    to_ = "à"
    or_ = "ou"
    domain = "domaine"
