Refresh_color = '#408040'
Archives_color = '#B2560D'
Edit_color = '#6060FF'
Trash_color = '#909090'
Log_color = 'grey'

Log_txt = 'Log'
New_txt = 'Nouveau'
Refresh_Txt = 'Rafraichir'
Archives_txt = 'Archive'
Trash_txt = 'Poubelle'
Exit_txt = ' X '

Do_delete_txt = 'Supprimer'
Do_archive_txt = 'Archiver'
Do_restore_txt = 'Restaurer'
Do_unarchive_txt = 'Désarchiver'
Do_edit_txt = 'Édition'

Init_txt = 'inititialisation'
Tracker_creation_txt = 'création suivi'
Updating_txt ='Mise à jour... '
Updated_txt = 'MàJ'
Empty_txt = 'Vide'
No_couriers_txt = 'Pas de Service Postaux'
No_idship_txt = 'N° indéfini'
Never_txt = 'jamais'
Ago_txt = 'il y a'
Unkown_status_txt = 'Status inconnu'
Default_product_txt = 'Envoi'
