Locale_setting = "fr_FR.utf8"

Long_date_format = "%a %d %b %y, %Hh%M"
Short_date_format = "%a %d %b %y"

log = "Log"
new = "Nouveau"
refresh = "Rafraichir"
archives = "Archive"
trash = "Poubelle"
exit = " X "
minimize = " _ "

ok = "OK"
cancel = "Annuler"
close = "Fermer"

delete = "Supprimer"
archive = "Archiver"
restore = "Restaurer"
unarchive = "Désarchiver"
edit = "Édition"

init = "inititialisation"
tracker_creation = "création suivi"
driver_creation = "création pilote"
updating = "MàJ..."
updated = "MàJ"
empty = "Vide"
no_couriers = "Pas de Service Postaux"
no_idship = "N° indéfini"
invalid_idship = "N° mal formé"
no_description = "Pas de description"
error_courier_update = "Erreur MàJ"
courier_doesnt_exist = "Service Postal inconnu"
never = "jamais"
ago = "il y a"

idship = "N° de suivi"
description = "Description"

unknown_status = "Status inconnu"
status_error = "Erreur"
default_product = "Envoi"

digits = "chiffres"
letters = "lettres"
zipcode = "code postal"
from_ = "de"
to_ = "à"
or_ = "ou"
